version: '3.9'

services:
  iam-service:
    build: .
    container_name: iam-service
    ports:
      - "8082:8082"
    environment:
      REDIS_HOST: 127.0.0.1
      POSTGRES_URL: jdbc:postgresql://iam-postgres:5432/iam_db
      POSTGRES_USER: kaka
      POSTGRES_PASSWORD: pie1711
      JWK_SSO_URL: http://my_keycloak:8080/realms/iam-realm/protocol/openid-connect/certs
    depends_on:
      redis:
        condition: service_started

    networks:
      - micro-network-1

  postgres:
    image: postgres:latest
    container_name: iam-postgres
    restart: always
    environment:
      POSTGRES_USER: kaka
      POSTGRES_PASSWORD: pie1711
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./iam_db.dump:/docker-entrypoint-initdb.d/iam_db.dump:ro
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh
    ports:
      - "5432:5432"
    networks:
      - micro-network-1

  redis:
    image: redis:latest
    container_name: iam_redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    hostname: iam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - micro-network-1

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: my_keycloak
    restart: always
    command: [ "start-dev" ]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://iam-postgres:5432/keycloak_db
      - KC_DB_USERNAME=kaka
      - KC_DB_PASSWORD=pie1711
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres
    networks:
      - micro-network-1

volumes:
  postgres-data:
  redis_data:
  keycloak_data:

networks:
  micro-network-1:
